### ISSUE TITLE
Absorbing/learning from ObjectDetection.jl

### ISSUE THREAD

**Issue by IanButterworth** [ianshmean/YOLO.jl#15]
As it turns out from the `#machine-learning` slack channel, @r3tex has also developed a YOLO implementation, but in flux: https://github.com/r3tex/ObjectDetector.jl

There's a few really nice things about how it's been implemented:
- YOLOv3 implementation, including the newer layer types i.e. `route`, `reorg` etc.
- Automatic conversion of YOLO models from `.cfg` to Flux models!
- Auto loading of `.weights` files into the auto-generated flux models!
- Flux implementation

@r3tex has kindly welcomed absorbing his work into this package, which I think could be good for these reasons:
- gets closer to having all YOLO model types implemented
- help push for switchable backends (Knet +Flux)
- @Ybakman is actively working on training this Knet implementation, so it would be good to be able to share that implementation across all models + backends

The switchable backend could be important as YOLO can be pretty memory intensive, so for restrictive platforms it could be nice to try both Knet and Flux.

I'm keen to see what people think. Absorb and enable switchable backends? Replace our manually built models with the auto-generated approach?

**Comment by iuliancioarca** [comment]
I would somehow keep both approaches. Automatic generation is quite elegant(although I tried running the example and generating the chains took approx. 20 min; maybe can be improved) and I would use it for stock models. On the other hand, the manually written models are more beginner friendly and could be a good Julia selling point for beginners( hey look at this Yolo implementation in Julia! You can also learn how the thing works without diving into C or other cryptic implementation). It could also be a friendlier starting point for custom models.

**Comment by r3tex** [comment]
Hmm. 20 minutes sounds excessive. It takes a couple of seconds on my machine. Are you low on RAM? An important advantage of this method is that I've verified that it produces the exact same results as the C darknet implementation so you can be sure there's no accuracy penalty or anything like that.

**Comment by iuliancioarca** [comment]
It must be something on my side. I run the code and get all those pretty prints when parsing .cfg. then takes 20min to build the chains. After the chain build is finished I get some error with setindex ( I'm not near a pc at the moment, but I'll post the exact error and line). My machine doesn't have a gpu, so I got some Cuarrays errors. I see the Yolo constructor has some gpu() instructions but it doesn't error out on those lines. System Ram is 16GB and julia version 1.1.1. Anyway, I don't want to shift the attention from the current topic with my issue. Maybe it's best to continue the discussion on a separate thread.

**Comment by IanButterworth** [comment]
There were issues with ObjectDetector.jl that made loading very slow on CPU (unexpected float64 issues), which are fixed now. https://github.com/r3tex/ObjectDetector.jl

We decided to keep that approach separate from this repo given the benefits of each listed above.
