### ISSUE TITLE
Cross-platform support progress

### ISSUE THREAD

**Issue by IanButterworth** [ianshmean/YOLO.jl#8]
- [x] Linux
- [x] MacOS
- [x] Windows
- [x] ARM
- [ ] FreeBSD - FileIO errors (no JPEG decode delegate) https://github.com/JuliaIO/FileIO.jl/issues/236

**Comment by iuliancioarca** [comment]
I tried updating to latest master but got stuck at this error:
`
ERROR: Unsatisfiable requirements detected for package Knet [1902f260]:
 Knet [1902f260] log:
 ├─possible versions are: [0.7.3, 0.8.0-0.8.5, 0.9.0-0.9.2, 1.0.0-1.0.1, 1.1.0-1.1.2, 1.2.0-1.2.6] or uninstalled
 └─restricted to versions 1.2.7-* by YOLO [af39948a] — no versions left
   └─YOLO [af39948a] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─YOLO [af39948a] is fixed to version 0.1.0
`
Is there a Knet 1.2.7 version?(I updated Knet but still get the same error)

**Comment by IanButterworth** [comment]
Ah that’s because there’s an update to Knet that’s not released yet that I’m trying out. Try checking out Knet master

**Comment by iuliancioarca** [comment]
Solved! Thanks!
